---
- hosts: alderaan-new

  tasks:
  - name: install lxc-dev module dependencies
    apt: name=lxc-dev state=present
  - name: install lxc-python2
    pip: name=lxc-python2 state=present
  - name: Create new LXC container
    lxc_container:
      backing_store: lvm
      container_log: True
      fs_size: 5G
      fs_type: ext4
      lv_name: lv_test
      name: test
      thinpool: tp_lxc
      vg_name: vg_alderaan
